services:
  movienite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "23245:8000"
    volumes:
      - ./movies.csv:/app/movies.csv
    container_name: movienite-container
