[project]
name = "movienite"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.128.0",
    "requests>=2.32.5",
    "tldextract>=5.3.1",
    "uvicorn>=0.40.0",
]
